http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths:
      - '/ip'
  
  api2:
    host: localhost
    paths:
      - '/todos/*'
      - '/users'
      - '/users/*'

serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org/'
    
  httpbin2:
    url: 'https://jsonplaceholder.typicode.com'
  
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
      - api2
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin2 
              changeOrigin: true
  # pipline_1:
  #   apiEndpoints:
  #     - api2
  #   policies:
  #   # Uncomment `key-auth:` when instructed to in the Getting Started guide.
  #     - key-auth
  #     - proxy:
  #         - action:
  #             serviceEndpoint: httpbin2 
  #             changeOrigin: true
